//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSQuickAssets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSQuickAssets.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files.
        /// </summary>
        public static string Assets_AddFiles {
            get {
                return ResourceManager.GetString("Assets_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string Assets_AddFolder {
            get {
                return ResourceManager.GetString("Assets_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder (including subfolders).
        /// </summary>
        public static string Assets_AddFolderWithSubfolders {
            get {
                return ResourceManager.GetString("Assets_AddFolderWithSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        public static string Assets_AddGroup {
            get {
                return ResourceManager.GetString("Assets_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute action &apos;{0}&apos; from set &apos;{1}&apos;.
        /// </summary>
        public static string Assets_CannotExecuteActionFromSet {
            get {
                return ResourceManager.GetString("Assets_CannotExecuteActionFromSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide
        ///Ctrl+Click: Exit.
        /// </summary>
        public static string Main_Close_Tooltip {
            get {
                return ResourceManager.GetString("Main_Close_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Location.
        /// </summary>
        public static string OpenFileLocation {
            get {
                return ResourceManager.GetString("OpenFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photoshop is busy.
        /// </summary>
        public static string PSStatus_Busy {
            get {
                return ResourceManager.GetString("PSStatus_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was cancelled.
        /// </summary>
        public static string PSStatus_Cancelled {
            get {
                return ResourceManager.GetString("PSStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured.
        /// </summary>
        public static string PSStatus_COMError {
            get {
                return ResourceManager.GetString("PSStatus_COMError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to communicate with Photoshop.
        /// </summary>
        public static string PSStatus_Failed {
            get {
                return ResourceManager.GetString("PSStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string PSStatus_FileNotFound {
            get {
                return ResourceManager.GetString("PSStatus_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path.
        /// </summary>
        public static string PSStatus_IllegalArgument {
            get {
                return ResourceManager.GetString("PSStatus_IllegalArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format.
        /// </summary>
        public static string PSStatus_InvalidFileFormat {
            get {
                return ResourceManager.GetString("PSStatus_InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path.
        /// </summary>
        public static string PSStatus_InvalidFilePath {
            get {
                return ResourceManager.GetString("PSStatus_InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documents open.
        /// </summary>
        public static string PSStatus_NoDocumentsOpen {
            get {
                return ResourceManager.GetString("PSStatus_NoDocumentsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has no selection.
        /// </summary>
        public static string PSStatus_NoSelection {
            get {
                return ResourceManager.GetString("PSStatus_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photoshop is not running.
        /// </summary>
        public static string PSStatus_NotRunning {
            get {
                return ResourceManager.GetString("PSStatus_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string PSStatus_Success {
            get {
                return ResourceManager.GetString("PSStatus_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Assets.
        /// </summary>
        public static string SelectAssets {
            get {
                return ResourceManager.GetString("SelectAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add mask from selection.
        /// </summary>
        public static string Settings_AddMaskIfDocumentHasSelection {
            get {
                return ResourceManager.GetString("Settings_AddMaskIfDocumentHasSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If document has a selection, a mask will be applied to added layer.
        /// </summary>
        public static string Settings_AddMaskIfDocumentHasSelection_Tooltip {
            get {
                return ResourceManager.GetString("Settings_AddMaskIfDocumentHasSelection_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On Top.
        /// </summary>
        public static string Settings_AlwaysOnTop {
            get {
                return ResourceManager.GetString("Settings_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keeps assets window above all other windows.
        /// </summary>
        public static string Settings_AlwaysOnTop_Tooltip {
            get {
                return ResourceManager.GetString("Settings_AlwaysOnTop_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string Settings_CheckForUpdates {
            get {
                return ResourceManager.GetString("Settings_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide window if clicked outside.
        /// </summary>
        public static string Settings_HideIfClickedOutside {
            get {
                return ResourceManager.GetString("Settings_HideIfClickedOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window will hide if deactivated.
        /// </summary>
        public static string Settings_HideIfClickedOutside_Tooltip {
            get {
                return ResourceManager.GetString("Settings_HideIfClickedOutside_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings and close this window.
        /// </summary>
        public static string Settings_SaveAndClose {
            get {
                return ResourceManager.GetString("Settings_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save setting:.
        /// </summary>
        public static string Settings_SavingConfigFailed {
            get {
                return ResourceManager.GetString("Settings_SavingConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set config value:.
        /// </summary>
        public static string Settings_SetValueFailed {
            get {
                return ResourceManager.GetString("Settings_SetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Size.
        /// </summary>
        public static string Settings_ThumbnailSize {
            get {
                return ResourceManager.GetString("Settings_ThumbnailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window open/close hotkey.
        /// </summary>
        public static string Settings_ToggleWindowHotkey {
            get {
                return ResourceManager.GetString("Settings_ToggleWindowHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a key combination to assign.
        ///Delete or Backspace to clear.
        ///Esc to cancel..
        /// </summary>
        public static string Settings_ToggleWindowHotkey_Tooltip {
            get {
                return ResourceManager.GetString("Settings_ToggleWindowHotkey_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change &quot;Window open/close hotkey&quot;:.
        /// </summary>
        public static string Settings_ToggleWindowHotkeyFailed {
            get {
                return ResourceManager.GetString("Settings_ToggleWindowHotkeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Taskbar_Exit {
            get {
                return ResourceManager.GetString("Taskbar_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Terminal.
        /// </summary>
        public static string Taskbar_ToggleTerminal {
            get {
                return ResourceManager.GetString("Taskbar_ToggleTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string Update_Available {
            get {
                return ResourceManager.GetString("Update_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current:.
        /// </summary>
        public static string Update_Current {
            get {
                return ResourceManager.GetString("Update_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download:.
        /// </summary>
        public static string Update_Download {
            get {
                return ResourceManager.GetString("Update_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New:.
        /// </summary>
        public static string Update_New {
            get {
                return ResourceManager.GetString("Update_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSQuickAssets.
        /// </summary>
        public static string Window_MainWindow {
            get {
                return ResourceManager.GetString("Window_MainWindow", resourceCulture);
            }
        }
    }
}
