//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSQuickAssets.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSQuickAssets.Resources.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as Layer.
        /// </summary>
        public static string Assets_AddAsLayer {
            get {
                return ResourceManager.GetString("Assets_AddAsLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files.
        /// </summary>
        public static string Assets_AddFiles {
            get {
                return ResourceManager.GetString("Assets_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add asset to Photoshop.
        /// </summary>
        public static string Assets_AddingToPhotoshopFailed {
            get {
                return ResourceManager.GetString("Assets_AddingToPhotoshopFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute action &apos;{0}&apos; from set &apos;{1}&apos;.
        /// </summary>
        public static string Assets_CannotExecuteActionFromSet {
            get {
                return ResourceManager.GetString("Assets_CannotExecuteActionFromSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Empty Group.
        /// </summary>
        public static string Assets_CreateEmptyGroup {
            get {
                return ResourceManager.GetString("Assets_CreateEmptyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Assets.
        /// </summary>
        public static string Assets_NothingAdded {
            get {
                return ResourceManager.GetString("Assets_NothingAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open as New Document.
        /// </summary>
        public static string Assets_OpenAsNewDoc {
            get {
                return ResourceManager.GetString("Assets_OpenAsNewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Assets_OpenWithShell {
            get {
                return ResourceManager.GetString("Assets_OpenWithShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Explorer.
        /// </summary>
        public static string Assets_ShowInExplorer {
            get {
                return ResourceManager.GetString("Assets_ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset(s).
        /// </summary>
        public static string GroupAssetCount {
            get {
                return ResourceManager.GetString("GroupAssetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string Mouse_Click {
            get {
                return ResourceManager.GetString("Mouse_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Click.
        /// </summary>
        public static string Mouse_CtrlClick {
            get {
                return ResourceManager.GetString("Mouse_CtrlClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photoshop is busy.
        /// </summary>
        public static string PSStatus_Busy {
            get {
                return ResourceManager.GetString("PSStatus_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was cancelled.
        /// </summary>
        public static string PSStatus_Cancelled {
            get {
                return ResourceManager.GetString("PSStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured.
        /// </summary>
        public static string PSStatus_COMError {
            get {
                return ResourceManager.GetString("PSStatus_COMError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to communicate with Photoshop.
        /// </summary>
        public static string PSStatus_Failed {
            get {
                return ResourceManager.GetString("PSStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string PSStatus_FileNotFound {
            get {
                return ResourceManager.GetString("PSStatus_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path.
        /// </summary>
        public static string PSStatus_IllegalArgument {
            get {
                return ResourceManager.GetString("PSStatus_IllegalArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format.
        /// </summary>
        public static string PSStatus_InvalidFileFormat {
            get {
                return ResourceManager.GetString("PSStatus_InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path.
        /// </summary>
        public static string PSStatus_InvalidFilePath {
            get {
                return ResourceManager.GetString("PSStatus_InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documents open.
        /// </summary>
        public static string PSStatus_NoDocumentsOpen {
            get {
                return ResourceManager.GetString("PSStatus_NoDocumentsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has no selection.
        /// </summary>
        public static string PSStatus_NoSelection {
            get {
                return ResourceManager.GetString("PSStatus_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photoshop is not running.
        /// </summary>
        public static string PSStatus_NotRunning {
            get {
                return ResourceManager.GetString("PSStatus_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string PSStatus_Success {
            get {
                return ResourceManager.GetString("PSStatus_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Group.
        /// </summary>
        public static string RemoveGroup {
            get {
                return ResourceManager.GetString("RemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Images.
        /// </summary>
        public static string SelectImages {
            get {
                return ResourceManager.GetString("SelectImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Settings_High {
            get {
                return ResourceManager.GetString("Settings_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Settings_Low {
            get {
                return ResourceManager.GetString("Settings_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Settings_Medium {
            get {
                return ResourceManager.GetString("Settings_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail quiality.
        /// </summary>
        public static string Settings_ThumbnailQuality {
            get {
                return ResourceManager.GetString("Settings_ThumbnailQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher quality can consume more RAM.
        /// </summary>
        public static string Settings_ThumbnailQuality_Tooltip {
            get {
                return ResourceManager.GetString("Settings_ThumbnailQuality_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version:.
        /// </summary>
        public static string Update_Current {
            get {
                return ResourceManager.GetString("Update_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download:.
        /// </summary>
        public static string Update_Download {
            get {
                return ResourceManager.GetString("Update_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Update_Later {
            get {
                return ResourceManager.GetString("Update_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version:.
        /// </summary>
        public static string Update_New {
            get {
                return ResourceManager.GetString("Update_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Whats New.
        /// </summary>
        public static string Update_OpenChangelog {
            get {
                return ResourceManager.GetString("Update_OpenChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Download Page.
        /// </summary>
        public static string Update_OpenDownloadPage {
            get {
                return ResourceManager.GetString("Update_OpenDownloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version of PSQuickAssets is Available!.
        /// </summary>
        public static string Update_UpdateAvailable {
            get {
                return ResourceManager.GetString("Update_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSQuickAssets Update.
        /// </summary>
        public static string Update_WindowTitle {
            get {
                return ResourceManager.GetString("Update_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Used: {0}.
        /// </summary>
        public static string Uses {
            get {
                return ResourceManager.GetString("Uses", resourceCulture);
            }
        }
    }
}
